tippy('#albums-teens', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Teens</h1><ul><li>Bruce Cockburn, <a href="https://open.spotify.com/album/2SPw42NwLiAzaaFa8qly2H?si=CuH6k5dZT1GbObJ2E-unjQ">Anything Anytime Anywhere</a> (2001)</li><li>Bruce Cockburn, <a href="https://open.spotify.com/album/4YDbl2wUdoTpyErcBzIS74?si=Xobu3VNmTrS0lH5zNlnR1Q">Speechless</a> (2005)</li><li>Bruce Hornsby, <a href="https://open.spotify.com/album/3krJt11TsETPI3fmKao7mx?si=5KEFLvx3SvOvYi269GEYhg">Halcyon Days</a> (2004)</li><li>Coldplay, <a href="https://open.spotify.com/album/6ZG5lRT77aJ3btmArcykra?si=-D0SEOLbSoOpA972ojYGlg">Parachutes</a> (2000)</li><li>Coldplay, <a href="https://open.spotify.com/album/1CEODgTmTwLyabvwd7HBty?si=q1OZyeEURJeSJt7nbfb87Q">Viva La Vida</a> (2008)</li><li>Counting Crows, <a href="https://open.spotify.com/album/50oL8ADjfT0n9gVoMpDwBy?si=2-GHrtIASCq3yLOYofTASQ">Hard Candy</a> (2002)</li><li>Inlet Sound, <a href="https://open.spotify.com/album/3U43E56TUQJ4PquiPwRtoP?si=V7us3KLVTuGRCTupSOhZNw">The Romantics</a> (2012)</li><li>Jack Johnson, <a href="https://open.spotify.com/album/7tTc46dNdE6GGuiQsssWxo?si=wRHZna_HQb-966mnU8CnKA">In Between Dreams</a> (2005)</li><li>John Mayer, <a href="https://open.spotify.com/album/3yHOaiXecTJVUdn7mApZ48?si=hwkf9N77Tie1le2QZ3KFbg">Room for Squares</a> (2001)</li><li>Kruger Brothers, <a href="https://open.spotify.com/album/1xOSi0H9sG36iZQl0xTK5i?si=CugiQvXyQOuoFboE2dq0aQ">The Suite, Vol. 1</a> (2007)</li><li>LCD Soundsystem, <a href="https://open.spotify.com/album/1R8kkopLT4IAxzMMkjic6X?si=ZKOPRcC-SfO_xJahT32Kgw">Sound of Silver</a> (2007)</li><li>Mark Knopfler &amp; Emmylou Harris, <a href="https://open.spotify.com/album/6oGCz3d9MqAB6OVMUOLibu?si=vrBq3nlnSlqDWVQthsaVRg">All The Roadrunning</a> (2006)</li><li>Michael McDonald, <a href="https://open.spotify.com/album/6GGLCPU6muUmk6kNU2MxG4?si=lWjnO9E9TIiE-r9A6agbJg">Motown</a> (2003)</li><li>Neutral Milk Hotel, <a href="https://open.spotify.com/album/5COXoP5kj2DWfCDg0vxi4F?si=hKzztpO8RN6kMxxW3GIwaA">In the Aeroplane Over the Sea</a> (1998)</li><li>Taylor Swift, <a href="https://open.spotify.com/album/1EoDsNmgTLtmwe1BDAVxV5?si=7UXR3R7EQo6Sco_6ayB_yg">Red</a> (2012)</li><li>Tommy Emmanuel, <a href="https://open.spotify.com/album/3jiBE7W0rwVucBUASlT0n5?si=2lMK5E4gR1iQ2xnv1hADYQ">Endless Road</a> (2005)</li><li>Tommy Emmanuel, <a href="https://open.spotify.com/album/3BBp2IUHdmFsn3uwAxh7Ur?si=4D7lUiubSPiwBIkrdt0xjg">The Mystery</a> (2006)</li><li>Tommy Emmanuel, <a href="https://open.spotify.com/album/5AUk0GEue5ON8pPIA8a7uF?si=HYDFmuqgTqm3NuOMr4IJqg">Center Stage</a> (2008)</li><li>Washed Out, <a href="https://open.spotify.com/album/72b7KBNzYH54BtZ5FBSFqi?si=mxK36G6jQYOQz_T3GwbK8Q">Paracosm</a> (2013)</li><li>Wax, <a href="https://open.spotify.com/album/7ovHfGslKaw6jb9GRVkVMo?si=Fsn5lmpGQiKUky_jovEhJA">Eviction Notice</a> (2011)</li><li>Wax, <a href="https://open.spotify.com/album/7ovHfGslKaw6jb9GRVkVMo?si=cQwWsaczSt-iZTE1HdoOww">Scrublife</a> (2011)</li></ul></div>'
});