tippy('#notes', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Notes</h1><ul><li><a class="internal-link" href="/professional-development-in-data-science/" id="professional-development-in-data-science">Professional development in data science</a></li><li><a class="internal-link" href="/to-go-viral-go-to-all-that-trouble/" id="to-go-viral-go-to-all-that-trouble">To go viral, go to all that trouble</a></li><li><a class="internal-link" href="/favourite-questions/" id="favourite-questions">Favourite questions</a></li><li><a class="internal-link" href="/striving-play/" id="striving-play">Striving play</a></li><li><a class="internal-link" href="/achievement-play/" id="achievement-play">Achievement play</a></li><li><a class="internal-link" href="/stupid-games/" id="stupid-games">Stupid games</a></li><li><a class="internal-link" href="/mind-positivity/" id="mind-positivity">Mind positivity</a></li><li><a class="internal-link" href="/maximize-pleasure/" id="maximize-pleasure">Maximize pleasure</a></li><li><a class="internal-link" href="/personal-phd/" id="personal-phd">The personal PhD</a></li><li><a class="internal-link" href="/tidy-up/" id="tidy-up">Tidy up so you can make a useful mess</a></li><li><a class="internal-link" href="/aesthetic-bullseye/" id="aesthetic-bullseye">The aesthetic bullseye</a></li><li><a class="internal-link" href="/everything-i-know-about-chess/" id="everything-i-know-about-chess">Everything I know about chess</a></li><li><a class="internal-link" href="/roam-as-a-slip-box/" id="roam-as-a-slip-box">Roam as a slip-box</a></li><li><a class="internal-link" href="/how-to-invest-in-index-funds/" id="how-to-invest-in-index-funds">How to invest in index funds, for Canadians</a></li><li><a class="internal-link" href="/laptop-setup/" id="laptop-setup">My laptop setup</a></li></ul></div>'
});