tippy('#commentaries', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Commentaries</h1><h2 id="articles">Articles</h2><ul><li><a class="internal-link" href="/solved-conversations/" id="solved-conversations">Solved conversations — Aaron Z. Lewis</a></li><li><a class="internal-link" href="/deep-laziness/" id="deep-laziness">Deep laziness — Sarah Perry</a></li><li><a class="internal-link" href="/levels-of-action/" id="levels-of-action">Levels of action — Alyssa Vance</a></li><li><a class="internal-link" href="/research-as-a-stochastic-decision-process/" id="research-as-a-stochastic-decision-process">Research as a stochastic decision process — Jacob Steinhardt</a></li><li><a class="internal-link" href="/pushing-and-pulling-goals/" id="pushing-and-pulling-goals">Pushing and pulling goals — Scott Alexander</a></li><li><a class="internal-link" href="/prototyping-at-the-speed-of-thought/" id="prototyping-at-the-speed-of-thought">Prototyping at the speed of thought — Tom Chi</a></li><li><a class="internal-link" href="/ideological-turing-test/" id="ideological-turing-test">The Ideological Turing test — Bryan Caplan</a></li></ul><h2 id="books">Books</h2><ul><li><a class="internal-link" href="/clear-atomic-habits/" id="clear-atomic-habits">Review: Atomic Habits — James Clear</a></li><li><a class="internal-link" href="/hofstadter-godel-escher-bach/" id="hofstadter-godel-escher-bach">Summary: Gödel, Escher, Bach — Douglas Hofstadter</a></li><li><a class="internal-link" href="/haidt-righteous-mind/" id="haidt-righteous-mind">Summary: The Righteous Mind — Jonathan Haidt</a></li><li><a class="internal-link" href="/goleman-and-davidson-altered-traits/" id="goleman-and-davidson-altered-traits">Summary: Altered Traits — Daniel Goleman and Richard Davidson</a></li><li><a class="internal-link" href="/harris-free-will/" id="harris-free-will">Summary: Free Will — Sam Harris</a></li><li><a class="internal-link" href="/thiel-zero-to-one/" id="thiel-zero-to-one">Summary: Zero to One — Peter Thiel</a></li></ul></div>'
});