tippy('#home', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'bottom',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><p>Welcome! I’m <a class="internal-link" href="/about-me/" id="about-me">David Laing</a>. I write to share my learning, to give more life to ideas that I think are underappreciated, and to make it easier for my future friends to find me.</p><p>The most important thing I’ve ever written is my essay, <a class="internal-link" href="/talk-more/" id="talk-more">If you’re good, you need to talk more</a>.</p><p>I write <a class="internal-link" href="/commentaries/" id="commentaries">commentaries</a> on notable essays from around the web. My favourites are on Sarah Perry’s idea of <a class="internal-link" href="/deep-laziness/" id="deep-laziness">deep laziness</a> and Alyssa Vance’s idea of <a class="internal-link" href="/levels-of-action/" id="levels-of-action">levels of action</a>.</p><p>I write about <a class="internal-link" href="/bookshelf/" id="bookshelf">books</a>. Most appreciated is my review of James Clear’s <a class="internal-link" href="/atomic-habits/" id="atomic-habits">Atomic Habits</a>, and most underrated is my summary of Jonathan Haidt’s <a class="internal-link" href="/righteous-mind/" id="righteous-mind">The Righteous Mind</a>.</p><p>I write about my hobbies and interests. See <a class="internal-link" href="/everything-i-know-about-chess/" id="everything-i-know-about-chess">everything I know about chess</a>, <a class="internal-link" href="/how-to-use-roam-as-a-slip-box/" id="how-to-use-roam-as-a-slip-box">how to use Roam as a slip-box</a>, and <a class="internal-link" href="/covers-shouldnt-just-be-for-musicians/" id="covers-shouldnt-just-be-for-musicians">Covers shouldn’t just be for musicians</a>.</p><p>Lastly, I write <a class="internal-link" href="/notes/" id="notes">notes</a>. I think of them as atomic proto-essays, or mega-tweets, in the style of Andy Matuschak’s <a class="external-link" href="https://notes.andymatuschak.org/z4SDCZQeRo4xFEQ8H4qrSqd68ucpgE6LU155C">evergreen notes</a>. Here are a few notes that are on my mind:</p><ul><li><a class="internal-link" href="/aesthetic-bullseye/" id="aesthetic-bullseye">The aesthetic bullseye</a></li><li><a class="internal-link" href="/tidy-up/" id="tidy-up">Tidy up so you can make a useful mess</a></li><li><a class="internal-link" href="/personal-phd/" id="personal-phd">The personal PhD</a></li></ul></div>'
});