tippy('#books-teens', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Teens</h1><ul><li>Barron, The Great Tree of Avalon trilogy (2006)</li><li>Barron, The Lost Years of Merlin Saga (2000) ★</li><li>Bock, The Ash Garden (2001)</li><li>Bradbury, Fahrenheit 451 (1953)</li><li>Brooks, The Sword of Shannara (1977)</li><li>Brown, The Da Vinci Code (2003)</li><li>Campbell, A Joseph Campbell Companion (1991)</li><li>Card, Ender’s Saga (1996) ★</li><li>Card, Ender’s Shadow (1999) ★</li><li>Clarke, 2001: A Space Odyssey (1968)</li><li>Clavell, Tai-Pan (1966)</li><li>Crichton, Jurassic Park (1990)</li><li>Czuchlewski, The Muse Asylum (2001)</li><li>Dawkins, The God Delusion (2006)</li><li>Dawkins, Unweaving the Rainbow (1998)</li><li>Emerson, Self-Reliance and Other Essays (1844)</li><li>Findley, The Butterfly Plague (1969)</li><li>Franklin, The Autobiography of Benjamin Franklin (1791)</li><li>Golding, Lord of the Flies (1954)</li><li>Hemingway, The Old Man and the Sea (1952)</li><li>Herbert, Dune (1965)</li><li>Hesse, Siddhartha (1922)</li><li>Hill, The Book of Negroes (2007)</li><li>Hinton, The Outsiders (1967)</li><li>Holt, Why Does the World Exist? (2011)</li><li>Homer, The Iliad (-750)</li><li>Homer, The Odyssey (-700)</li><li>Jordan, The Wheel of Time 1-3 (1990)</li><li>Kadare, Broken April (1978)</li><li>Kay, The Fionavar Tapestry (1986)</li><li>Kay, Ysabel (2007)</li><li>Larson, The Far Side Gallery (1984)</li><li>Lee, To Kill a Mockingbird (1960)</li><li>Lightman, Einstein’s Dreams (1992)</li><li>Martel, Life of Pi (2001) ★</li><li>Miller, The Crucible (1953)</li><li>Palahniuk, Fight Club (1996)</li><li>Paolini, The Inheritance Cycle 1-3 (2002)</li><li>Patterson, Maximum Ride (2005)</li><li>Paulsen, Brian’s Saga 1-2 (1996)</li><li>Pullman, His Dark Materials (2000) ★</li><li>Rushdie, The Satanic Verses (1988)</li><li>Saint-Exupéry, The Little Prince (1943)</li><li>Salinger, The Catcher in the Rye (1951)</li><li>Shakespeare, A Midsummer Night’s Dream (1595)</li><li>Shakespeare, Hamlet (1603)</li><li>Shakespeare, Romeo and Juliet (1595)</li><li>Smith, The World’s Religions (1958)</li><li>Spong, A New Christianity for a New World (2001)</li><li>Swift, Gulliver’s Travels (1726)</li><li>Thoreau, Walden (1854)</li><li>Tolkien, The Lord of the Rings (1955)</li><li>Verne, Twenty Thousand Leagues Under the Sea (1869)</li><li>Voltaire, Candide (1759)</li><li>Vonnegut, God Bless You, Mr. Rosewater (1965)</li><li>Wilson, Spin (2005)</li><li>Wright, A Short History of Progress (2004)</li><li>Wyndham, The Chrysalids (1955)</li></ul></div>'
});