tippy('#albums-rap', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Rap</h1><ul><li>Anderson .Paak, <a href="https://open.spotify.com/album/4VFG1DOuTeDMBjBLZT7hCK?si=H3MLe7PYSuOlTSv6a4CsOw">Malibu</a> (2016)</li><li>BROCKHAMPTON, <a href="https://open.spotify.com/album/67smHJOf5YlFwad6dAlppm?si=5M89dUBzTOaAhu3gGO0_cg">SATURATION I, II, &amp; III</a> (2017)</li><li>Chance the Rapper, <a href="https://open.spotify.com/album/2VBcztE58pBKjIDS5oEgFh?si=T1SjpH_wRaiEdyxCAP5HMw">Acid Rap</a> (2013)</li><li>Kanye West, <a href="https://open.spotify.com/album/4Uv86qWpGTxf7fU7lG5X6F?si=7PDm7z7gQwCsdqC6CYfAcQ">The College Dropout</a> (2004)</li><li>Kanye West, <a href="https://open.spotify.com/album/5ll74bqtkcXlKE7wwkMq4g?si=ZmdTIlXiQFq7w5941uNCuw">Late Registration</a> (2005)</li><li>Kanye West, <a href="https://open.spotify.com/album/5fPglEDz9YEwRgbLRvhCZy?si=QN53I8ebQqmqZnSLT4_A-Q">Graduation</a> (2007)</li><li>Kanye West, <a href="https://open.spotify.com/album/20r762YmB5HeofjMCiPMLv?si=4J7QkzFdSfSzeA7LQJZ9Ww">My Beautiful Dark Twisted Fantasy</a> (2010)</li><li>Kanye West, <a href="https://open.spotify.com/album/7gsWAHLeT0w7es6FofOXk1?si=kvX-x8XwRAKi0kXVzlrBsQ">The Life of Pablo</a> (2016)</li><li>Kendrick Lamar, <a href="https://open.spotify.com/album/1bkN9nIkkCnXeG4yitVS1J?si=8lgZUaj7QcqvG7JfZaQAGA">Section.80</a> (2011)</li><li>Kendrick Lamar, <a href="https://open.spotify.com/album/6PBZN8cbwkqm1ERj2BGXJ1?si=4xqRq2CGRpG-lb_7q7y54Q">good kid, m.A.A.d city</a> (2012)</li><li>Kendrick Lamar, <a href="https://open.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP?si=fo69BnRrSEWBFsTe03ylLg">To Pimp A Butterfly</a> (2015)</li><li>Lin-Manuel Miranda, <a href="https://open.spotify.com/album/1kCHru7uhxBUdzkm4gzRQc?si=PPLwy010Tc26N1RdEm_qSg">Hamilton</a> (2015)</li><li>Run the Jewels, <a href="https://open.spotify.com/album/7BUlAwJBzKyllRuDTKV8Ae?si=4B6vJqfEQCOILHDKauXb0w">Run the Jewels</a> (2013)</li><li>Run the Jewels, <a href="https://open.spotify.com/album/4Loc7NtCAo9mypHO6kbviD?si=9UW4axbXRkGh0TIkQLH-Kw">Run the Jewels 2</a> (2014)</li><li>Wax, <a href="https://open.spotify.com/album/7ovHfGslKaw6jb9GRVkVMo?si=Fsn5lmpGQiKUky_jovEhJA">Eviction Notice</a> (2011)</li><li>Wax, <a href="https://open.spotify.com/album/7ovHfGslKaw6jb9GRVkVMo?si=cQwWsaczSt-iZTE1HdoOww">Scrublife</a> (2011)</li><li>Wax, <a href="https://open.spotify.com/album/3lumObxzH6YVhxwOsgKXTF?si=l4MEUSmSQoaINGosH4rANA">The Cookout Chronicles</a> (2016)</li></ul></div>'
});