tippy('#albums-rock', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Rock</h1><ul><li>The Beatles, A Hard Day’s Night (1964)</li><li>The Beatles, Abbey Road (1969)</li><li>The Beatles, Beatles For Sale (1964)</li><li>The Beatles, Help! (1965)</li><li>The Beatles, Let It Be (1970)</li><li>The Beatles, Magical Mystery Tour (1967)</li><li>The Beatles, Please Please Me (1963)</li><li>The Beatles, Revolver (1966)</li><li>The Beatles, Rubber Soul (1965)</li><li>The Beatles, Sgt. Pepper’s Lonely Hearts Club Band (1967)</li><li>The Beatles, The White Album (1968)</li><li>The Beatles, With The Beatles (1963)</li><li>The Beths, Future Me Hates Me (2018)</li><li>Bruce Cockburn, Anything Anytime Anywhere (2001)</li><li>Bruce Cockburn, Speechless (2005)</li><li>Bruce Hornsby, Halcyon Days (2004)</li><li>Bruce Hornsby &amp; the Noisemakers, Bride of the Noisemakers (2011)</li><li>Bryan Adams, The Best of Me (1999)</li><li>Coldplay, Parachutes (2000)</li><li>Coldplay, Viva La Vida (2008)</li><li>Counting Crows, Hard Candy (2002)</li><li>Daft Punk, Random Access Memories (2013)</li><li>Fleetwood Mac, Dreams (1977)</li><li>John Mayer, Room for Squares (2001)</li><li>John Mayer, The Search for Everything (2017)</li><li>KC Roberts &amp; the Live Revolution, Between the Cracks (2012)</li><li>KC Roberts &amp; the Live Revolution, Good Life (2010)</li><li>KC Roberts &amp; the Live Revolution, Parkdale Funk 2 (2013)</li><li>LCD Soundsystem, Sound of Silver (2007)</li><li>The La’s, The La’s (1990)</li><li>Mark Knopfler, The Ragpicker’s Dream (2002)</li><li>Mark Knopfler &amp; Emmylou Harris, All The Roadrunning (2006)</li><li>Neutral Milk Hotel, In the Aeroplane Over the Sea (1998)</li><li>Paramore, After Laughter (2017)</li><li>Phil Collins, Testify (2002)</li><li>Phil Collins &amp; Mark Mancina, Tarzan (1999)</li><li>Pink Floyd, The Dark Side of the Moon (1973)</li><li>Radiohead, In Rainbows (2007)</li><li>Steely Dan, Aja (1977)</li><li>Tame Impala, Currents (2015)</li><li>Theo Katzman, Heartbreak Hits (2017)</li><li>Theo Katzman, Modern Johnny Sings (2020)</li><li>Theo Katzman, My Heart Is Live in Berlin (2019)</li><li>Theo Katzman, Romance Without Finance (2011)</li><li>Vampire Weekend, Father of the Bride (2019)</li><li>Vampire Weekend, Modern Vampires of the City (2013)</li><li>Van Morrison, Avalon Sunset (1989)</li></ul></div>'
});