tippy('#albums-rock', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Rock</h1><ul><li>The Beatles, <em>Please Please Me</em> (1963)</li><li>The Beatles, <em>Let It Be</em> (1970)</li><li>The Beatles, <em>Beatles For Sale</em> (1964)</li><li>The Beatles, <em>The White Album</em> (1968)</li><li>The Beatles, <em>Magical Mystery Tour</em> (1967)</li><li>The Beatles, <em>Sgt. Pepper’s Lonely Hearts Club Band</em> (1967)</li><li>The Beatles, <em>Revolver</em> (1966)</li><li>The Beatles, <em>Rubber Soul</em> (1965)</li><li>The Beatles, <em>Help!</em> (1965)</li><li>The Beatles, <em>Abbey Road</em> (1969)</li><li>The Beatles, <em>A Hard Day’s Night</em> (1964)</li><li>The Beatles, <em>With The Beatles</em> (1963)</li><li>The Beths, <em>Future Me Hates Me</em> (2018)</li><li>Bruce Hornsby, <em>Halcyon Days</em> (2004)</li><li>Bruce Hornsby &amp; the Noisemakers, <em>Bride of the Noisemakers</em> (2011)</li><li>Coldplay, <em>Parachutes</em> (2000)</li><li>Coldplay, <em>Viva La Vida</em> (2008)</li><li>Counting Crows, <em>Hard Candy</em> (2002)</li><li>Daft Punk, <em>Random Access Memories</em> (2013)</li><li>Fleetwood Mac, <em>Dreams</em> (1977)</li><li>John Mayer, <em>Room for Squares</em> (2001)</li><li>John Mayer, <em>The Search for Everything</em> (2017)</li><li>KC Roberts &amp; the Live Revolution, <em>Good Life</em> (2010)</li><li>KC Roberts &amp; the Live Revolution, <em>Parkdale Funk 2</em> (2013)</li><li>KC Roberts &amp; the Live Revolution, <em>Between the Cracks</em> (2012)</li><li>LCD Soundsystem, <em>Sound of Silver</em> (2007)</li><li>The La’s, <em>The La’s</em> (1990)</li><li>Mark Knopfler, <em>The Ragpicker’s Dream</em> (2002)</li><li>Mark Knopfler &amp; Emmylou Harris, <em>All The Roadrunning</em> (2006)</li><li>Neutral Milk Hotel, <em>In the Aeroplane Over the Sea</em> (1998)</li><li>Paramore, <em>After Laughter</em> (2017)</li><li>Phil Collins &amp; Mark Mancina, <em>Tarzan</em> (1999)</li><li>Pink Floyd, <em>The Dark Side of the Moon</em> (1973)</li><li>Radiohead, <em>In Rainbows</em> (2007)</li><li>Steely Dan, <em>Aja</em> (1977)</li><li>Tame Impala, <em>Currents</em> (2015)</li><li>Theo Katzman, <em>Heartbreak Hits</em> (2017)</li><li>Theo Katzman, <em>My Heart Is Live in Berlin</em> (2019)</li><li>Theo Katzman, <em>Modern Johnny Sings</em> (2020)</li><li>Theo Katzman, <em>Romance Without Finance</em> (2011)</li><li>Vampire Weekend, <em>Father of the Bride</em> (2019)</li><li>Vampire Weekend, <em>Modern Vampires of the City</em> (2013)</li><li>Van Morrison, <em>Avalon Sunset</em> (1989)</li></ul></div>'
});