tippy('#albums', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Albums</h1><p>For now, I’m only keeping track of albums I love. So, if it’s listed on any of these pages, I love it.</p><ul><li><a class="internal-link" href="/all-albums/" id="all-albums">All albums</a></li></ul><h2 id="when-i-first-heard-it">When I first heard it</h2><ul><li><a class="internal-link" href="/albums-in-the-past-year/" id="albums-in-the-past-year">In the past year</a></li><li><a class="internal-link" href="/albums-20s/" id="albums-20s">20s</a></li><li><a class="internal-link" href="/albums-teens/" id="albums-teens">Teens</a></li><li><a class="internal-link" href="/albums-childhood/" id="albums-childhood">Childhood</a></li></ul><h2 id="genres">Genres</h2><ul><li><a class="internal-link" href="/albums-alternative/" id="albums-alternative">Alternative</a></li><li><a class="internal-link" href="/albums-bluegrass/" id="albums-bluegrass">Bluegrass</a></li><li><a class="internal-link" href="/albums-christmas/" id="albums-christmas">Christmas</a></li><li><a class="internal-link" href="/albums-classical/" id="albums-classical">Classical</a></li><li><a class="internal-link" href="/albums-country/" id="albums-country">Country</a></li><li><a class="internal-link" href="/albums-electronic/" id="albums-electronic">Electronic</a></li><li><a class="internal-link" href="/albums-folk/" id="albums-folk">Folk</a></li><li><a class="internal-link" href="/albums-funk/" id="albums-funk">Funk</a></li><li><a class="internal-link" href="/albums-jazz/" id="albums-jazz">Jazz</a></li><li><a class="internal-link" href="/albums-live/" id="albums-live">Live</a></li><li><a class="internal-link" href="/albums-musicals/" id="albums-musicals">Musicals</a></li><li><a class="internal-link" href="/albums-pop/" id="albums-pop">Pop</a></li><li><a class="internal-link" href="/albums-r-and-b/" id="albums-r-and-b">R &amp; B</a></li><li><a class="internal-link" href="/albums-rap/" id="albums-rap">Rap</a></li><li><a class="internal-link" href="/albums-rock/" id="albums-rock">Rock</a></li></ul></div>'
});