tippy('#commentaries', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Commentaries</h1><h2 id="articles">Articles</h2><ul><li><a class="internal-link" href="/pushing-and-pulling-goals/" id="pushing-and-pulling-goals">Pushing and pulling goals — Scott Alexander</a></li><li><a class="internal-link" href="/ideological-turing-test/" id="ideological-turing-test">Ideological Turing test — Bryan Caplan</a></li><li><a class="internal-link" href="/solved-conversations/" id="solved-conversations">Solved conversations — Aaron Z. Lewis</a></li><li><a class="internal-link" href="/deep-laziness/" id="deep-laziness">Deep laziness — Sarah Perry</a></li><li><a class="internal-link" href="/levels-of-action/" id="levels-of-action">Levels of action — Alyssa Vance</a></li><li><a class="internal-link" href="/research-as-a-stochastic-decision-process/" id="research-as-a-stochastic-decision-process">Research as a stochastic decision process — Jacob Steinhardt</a></li></ul><h2 id="books">Books</h2><ul><li><a class="internal-link" href="/atomic-habits/" id="atomic-habits">Atomic Habits — James Clear</a></li><li><a class="internal-link" href="/godel-escher-bach/" id="godel-escher-bach">Godel, Escher, Bach in 34 propositions</a></li><li><a class="internal-link" href="/righteous-mind/" id="righteous-mind">The Righteous Mind — Jonathan Haidt</a></li></ul><h2 id="videos">Videos</h2><ul><li><a class="internal-link" href="/prototyping-at-the-speed-of-thought/" id="prototyping-at-the-speed-of-thought">Prototyping at the speed of thought — Tom Chi</a></li><li><a class="internal-link" href="/aesthetic-bullseye/" id="aesthetic-bullseye">The aesthetic bullseye – Hank Green</a></li></ul><h2 id="fiction">Fiction</h2><ul><li><a class="internal-link" href="/the-machine-stops/" id="the-machine-stops">E.M. Forster predicted 2020 in 1909</a></li></ul></div>'
});