tippy('#books-loved', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>Loved</h1><ul><li>Bach, Jonathan Livingston Seagull (1970)</li><li>Barron, The Lost Years of Merlin Saga (2000)</li><li>Card, Ender’s Saga (1996)</li><li>Card, Ender’s Shadow (1999)</li><li>Carnegie, How to Win Friends and Influence People (1936)</li><li>Caro, The Path to Power (1982)</li><li>Chabon, The Amazing Adventures of Kavalier &amp; Clay (2000)</li><li>Chiang, Exhalation: Stories (2019)</li><li>Christian, Algorithms to Live By (2016)</li><li>Ferrante, My Brilliant Friend (2011)</li><li>Forster, The Machine Stops (1909)</li><li>Frank, The Diary of a Young Girl (1947)</li><li>Gaiman, The Ocean at the End of the Lane (2013)</li><li>Gibson &amp; Sterling, The Difference Engine (1990)</li><li>Gleick, Isaac Newton (2003)</li><li>Gleick, The Information (2011)</li><li>Gowdy, Disneyland (1989)</li><li>Haidt, The Happiness Hypothesis (2005)</li><li>Haidt, <a class="internal-link" href="/haidt-righteous-mind/" id="haidt-righteous-mind">The Righteous Mind</a> (2012)</li><li>Harris, <a class="internal-link" href="/harris-free-will/" id="harris-free-will">Free Will</a> (2012)</li><li>Harris, Waking Up (2014)</li><li>Hawley, Before the Fall (2016)</li><li>Hofstadter, <a class="internal-link" href="/hofstadter-godel-escher-bach/" id="hofstadter-godel-escher-bach">Gödel, Escher, Bach</a> (1979)</li><li>Irving, A Prayer for Owen Meany (1989)</li><li>Joyce, Araby (1914)</li><li>Joyce, The Dead (1914)</li><li>King, On Writing (2000)</li><li>Martel, Life of Pi (2001)</li><li>McCarthy, The Road (2006)</li><li>McMurtry, <a class="internal-link" href="/mcmurtry-lonesome-dove/" id="mcmurtry-lonesome-dove">Lonesome Dove</a> (1985)</li><li>Miller, Know My Name (2019)</li><li>Nielsen, Reinventing Discovery (2011)</li><li>Nimmo, Children of the Red King 1-5 (2002-2006)</li><li>Pinker, How the Mind Works (1997)</li><li>Pinker, The Language Instinct (1994)</li><li>Pinker, The Sense of Style (2014)</li><li>Pullman, His Dark Materials (2000)</li><li>Rowling, Harry Potter 1-7 (2007)</li><li>Wallace, Both Flesh and Not: Essays (2012)</li><li>Wallace, Infinite Jest (1996)</li><li>Wallace, Oblivion (2004)</li><li>Watterson, Calvin and Hobbes (1985-1995)</li><li>Westover, Educated (2018)</li><li>Wickham, Advanced R (2014)</li><li>Yudkowsky, Harry Potter and the Methods of Rationality (2015)</li><li>Yudkowsky, <a href="https://yudkowsky.tumblr.com/writing">Intelligent Characters</a> (2014)</li><li>Yudkowsky, Rationality From AI to Zombies (2015)</li></ul></div>'
});