tippy('#about-me', {
    theme: 'light-border',
    arrow: false,
    allowHTML: true,
    placement: 'right',
    touch: false,
    maxWidth: 550,
    interactive: true,
    interactiveBorder: 1,
    content: '<div class="article-component"><h1>About me</h1><h2 id="whats-my-story">What’s my story?</h2><p>I grew up in Peterborough, Ontario. It was a wonderful and fortunate childhood, filled with fantasy novels, James Taylor albums, canoe trips, and swim meets.</p><p>I studied everything and nothing in McMaster University’s interdisciplinary <a class="external-link" href="https://en.wikipedia.org/wiki/McMaster_Arts_and_Science" target="_self">Arts &amp; Science program</a>, where I found my people.</p><p>After a year of teaching writing at a Niagara College in Welland, Ontario, I decided to train as a data scientist. I moved to the west coast to study in the first cohort of the <a class="external-link" href="https://masterdatascience.ubc.ca/" target="_self">Master of Data Science program</a> at the University of British Columbia.</p><p>I now live in Vancouver with my partner, Meg. I love listening to music, tinkering on the piano, playing blitz chess, and biking everywhere no matter how hard it’s raining.</p><h2 id="what-do-i-do-for-work">What do I do for work?</h2><ul><li>I’m a senior data scientist at <a class="external-link" href="https://imbellus.com/" target="_self">Imbellus</a>, a startup that makes cognitive assessments. The assessments look and feel like games, and their goal is to provide an alternative to traditional multiple-choice tests, which are great at measuring content mastery and memorization but not so great at measuring skills like decision-making, adaptability, or situational awareness. My job is to design and build scoring systems for these assessments.</li><li>Once per year, I teach a course on communication and argumentation in the <a class="external-link" href="https://masterdatascience.ubc.ca/" target="_self">Master of Data Science program</a> at the University of British Columbia. The course prepares students to communicate and reason effectively about data science topics and findings.</li><li>I also teach a course for Hyperlink Academy called <a class="external-link" href="https://hyperlink.academy/courses/write-a-micro-textbook/14" target="_self">Write a Micro-Textbook</a>. The course takes a small group of people through the process of creating a substantial work of instructional writing, in five weeks.</li></ul><h2 id="how-should-you-contact-me">How should you contact me?</h2><p>The best way is to send me a message on <a class="external-link" href="https://twitter.com/davidklaing" target="_self">Twitter</a>. You’re also welcome to email me at davidkendalllaing at gmail dot com.</p><h2 id="why-should-you-contact-me">Why should you contact me?</h2><p>Because then we might become friends! Perhaps you…</p><ul><li>know of something that I might find interesting.</li><li>read something on my site that <em>you</em> found interesting.</li><li>want to collaborate on a project.</li><li>want to meet me for a (virtual) coffee.</li></ul></div>'
});